apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: {{ .Values.namespace }}
  labels:
    app: java-app
spec:
  selector:
    matchLabels:
      app: java-app
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: "{{ .Values.image.repository }}"  # {"$imagepolicy": "flux-system:my-dockerhub-policy"}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}