name: Save Chart In Chart Museum

on:
 push:
   branches:
     - main
   paths:
     - 'app/**'

jobs:
 build:
   runs-on: self-hosted
   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Save Helm Chart to ChartMuseum
       run: |
        sudo helm package app/
        CHART_FILE=$(find . -name 'app-*.tgz' | head -n 1)
        sudo curl --data-binary "@${CHART_FILE}" "http://localhost:8080/api/charts?force=true"