name: Save Chart In Chart Museum

on:
 push:
   branches:
     - main
   paths:
     - 'appChart/**'

jobs:
 build:
   runs-on: self-hosted
   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Save Helm Chart to ChartMuseum
       run: |
        sudo cd appChart/
        sudo helm package .
        sudo curl --data-binary "@appChart-0.1.0.tgz" http://localhost:8080/api/charts

